### ISSUE TITLE
na_interpolation missing?

### ISSUE THREAD

**Issue by olli0601** [Hanyang97/Carlifornia-Covid19#1]
https://github.com/Hanyang97/Carlifornia-Covid19/blob/6100c8b0a9759bb17936e43f6687644bc8c91c38/m2rco/Second_trial.R#L196

Hi guys, I seem to be stuck with the error

> x2$grocery.pharmacy <- na_interpolation(x2$grocery.pharmacy, option = "linear")Error in na_interpolation(x2$grocery.pharmacy, option = "linear") :   could not find function "na_interpolation"

**Comment by Hanyang97** [comment]
na_interpolation is from the imputeTS package
