### ISSUE TITLE
cc melt

### ISSUE THREAD

**Issue by olli0601** [Hanyang97/Carlifornia-Covid19#2]
https://github.com/Hanyang97/Carlifornia-Covid19/blob/6100c8b0a9759bb17936e43f6687644bc8c91c38/m2rco/Second_trial.R#L92

Hi all, I am not sure if this is bad, but would be nice to fix the warning
 
> cc <- melt(cc, id.vars=c('countyFIPS','County.Name','State','stateFIPS'), variable.name='DATE', value.name='CASE')
Warning message:
In melt.data.table(cc, id.vars = c("countyFIPS", "County.Name",  :
  'measure.vars' [X1.22.20, X1.23.20, X1.24.20, X1.25.20, ...] are not all of the same type. By order of hierarchy, the molten data value column will be of type 'integer'. All measure variables not of type 'integer' will be coerced too. Check DETAILS in ?melt.data.table for more on coercion.

**Comment by Vidoushee05** [comment]
I removed the last column (full of NAs) which seemed to be causing the problem.
